### ISSUE TITLE
Docker storage needs a bit of setup documentation

### ISSUE THREAD

**Issue by ghost** [clustervision/trinityX#104]
We need a tiny bit of documentation for how to set up Docker storage on the controllers.

My setup:
- no LVM
- not 100GB storage available for containers

`docker-storage-setup` fails because of first item, and then the whole Docker registry doesn't start. I fixed it by adding this line to `/etc/sysconfig/docker-storage-setup`:

```
STORAGE_DRIVER=""
```

I haven't gotten around to working on the 100GB topic.

I don't think that we need to change the scripts, because different OS setups will require different backend setups. We should have a bit of doc though, maybe a few lines in the pre-installation requirements and a short paragraph to give examples of config.

**Comment by heatherLstephens** [comment]
we use the default
