### ISSUE TITLE
set an expiration date on a Loki user account to forbid access

### ISSUE THREAD

**Issue by jelenakoldan** [clustervision/trinityX#106]
At the moment ldap objects do not have an attribute dedicated to the expiration date of an account. 
We have a requirement to set and track down the expiration date of an account. Thus when some user account is about to expire, the user can be notified in order to extend or decline further usage of the account. In case that the user doesn't want to extend the account or doesn't reply, they shouldn't be able to access the account after the expiration date. Also, it should be possible to change the expiration date in case that the user wants a new extension.

**Comment by sibomarie** [comment]
not an issue any more
