### ISSUE TITLE
Move images out of the shared disk

### ISSUE THREAD

**Issue by dchirikov** [clustervision/trinityX#114]
Osimages now located in /trinity/images by default
In HA environment it should be HA disk (external NFS, shared disk or drbd).
BU luna do not need any HA disk. It is able to copy image files on 'osimage pack' operation
As a result images data copied in 3 places - 2 copy handled by drbd, and another copy - /trinity on passive node, which is usually located on /dev/sda

**Comment by hicham-a** [comment]
We favor shared storage over luna replication in the new design. Closing
