### ISSUE TITLE
Docker blocks CentOS to boot

### ISSUE THREAD

**Issue by dchirikov** [clustervision/trinityX#120]
N.B. subject a little bit scandalous, but issues is gone after 

```
yum erase docker-common-1.10.3-46.el7.centos.14.x86_64 docker-1.10.3-46.el7.centos.14.x86_64 docker-selinux-1.10.3-46.el7.centos.14.x86_64
```

Yesterday afternoon we noticed that some nodes did not came back after reboot.
KVM shows the following:
![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/6017800/19107814/5998e738-8aee-11e6-9706-b436b64a05ed.jpg)

Issue completely random - gone on reboot, but other nodes can stuck, etc. Hit rate is about 10-20%. Nodes is not available via net, and do not bring interface up. The exact point of the issue - right after switchroot to /sysroot.

After a while we managed to pick up some text data. I am afraid that's all we can get from it, as we are booting diskless and all the data and logs get wiped on boot.

[bug-screenlog.0.txt](https://github.com/clustervision/trinityX/files/510584/bug-screenlog.0.txt)

**Comment by heatherLstephens** [comment]
nonreproducible
