### ISSUE TITLE
Postfix listens only on localhost

### ISSUE THREAD

**Issue by krumstein** [clustervision/trinityX#132]
Postfix on the controller should listen at trusted interfaces and accept mails to controller.cluster domain

**Comment by dchirikov** [comment]
Strictly speaking we need to have postfix under pacemaker's control and spool directory on shared storage. But quick fix will be to tell zabbix to send its emails to localhost

**Comment by aphmschonewille** [comment]
Current TrinityX release has a vastly different H/A approach compared to previous releases. If this problem is still current, please let me know and the Issue will be reopened.
