### ISSUE TITLE
Domain name for controller

### ISSUE THREAD

**Issue by krumstein** [clustervision/trinityX#140]
I think it would be nice to add domains for controller nodes as well as for all other nodes. There can be issues with some software without a domain on controller. For example, by default,  zabbix sends a local email and such an error occurs in /var/log/maillog:
Nov  9 16:20:39 teahupoo postfix/smtp[31786]: 53624D45E7D4: to=<root@controller.localdomain>, orig_to=<root@controller>, relay=none, delay=0.07, delays=0.07/0/0/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=controller.localdomain type=AAAA: Host not found)
Nov  9 16:20:39 teahupoo postfix/cleanup[31785]: 72499D45E7A4: message-id=<2016110915203

**Comment by jflf-CV** [comment]
Wouldn't that be an issue with Luna and the way it deals with DHCP, than with 3X? We don't configure anything related to domain or networking in the images, as it's all provided by Luna.

**Comment by krumstein** [comment]
@dchirikov , what are your thoughts?

**Comment by heatherLstephens** [comment]
implemented
