### ISSUE TITLE
Openstack controller install script - missing dependencies

### ISSUE THREAD

**Issue by cedriccastagnede** [clustervision/trinityX#151]
Hello devopts,

When we install the openstack controller not as standalone, some dependencies missing during mariadb installation. Please see below: 
 ----->>>  Running post script: /root/trinityx/configuration/openstack/mariadb.sh  <<<-----

[ info ]   Starting MariaDB server.

bash: openssl: command not found

[ warn ]   store_password: usage: store_password variable password

[ ERROR ]  Error during post script: /root/trinityx/configuration/openstack/mariadb.sh

           Press Enter to continue.

Cheers,
Cédric

**Comment by hicham-a** [comment]
Hi Cédric,

Are you starting from a fresh CentOS minimal install?
The installer tries to generate a password for the database using openssl which it couldn't find

**Comment by jflf-CV** [comment]
I checked the dependency tree for Minimal, and indeed I can't find OpenSSL in it. I guess that the CentOS Minimal install from the ISO isn't that minimal after all.

OpenSSL is required by base, which we don't really want as it includes all sorts of services that are not very useful on servers.

I'll add openssl to the list of base packages. Thanks!

**Comment by cedriccastagnede** [comment]
Hello,

Yes, I've indeed started from a minimal centos image and OpenSSL is not in the minimal.

I also suggest you add centos-release-openstack-mitaka instead of writting on your own the repo file (openstack/additional-repos/CentOS-OpenStack-mitaka.repo).



================================================================================
 Package                 Arch   Version           Repository               Size
================================================================================
Installing:
 mariadb                 x86_64 3:10.1.18-3.el7   centos-openstack-mitaka 6.2 M
 mariadb-server          x86_64 3:10.1.18-3.el7   centos-openstack-mitaka  19 M
Installing for dependencies:
 libaio                  x86_64 0.3.109-13.el7    base                     24 k
 mariadb-common          x86_64 3:10.1.18-3.el7   centos-openstack-mitaka  63 k
 mariadb-errmsg          x86_64 3:10.1.18-3.el7   centos-openstack-mitaka 199 k
 perl-Compress-Raw-Bzip2 x86_64 2.061-3.el7       base                     32 k
 perl-Compress-Raw-Zlib  x86_64 1:2.061-4.el7     base                     57 k
 perl-DBD-MySQL          x86_64 4.023-5.el7       base                    140 k
 perl-DBI                x86_64 1.627-4.el7       base                    802 k
 perl-Data-Dumper        x86_64 2.145-3.el7       base                     47 k
 perl-IO-Compress        noarch 2.061-2.el7       base                    260 k
 perl-Net-Daemon         noarch 0.48-5.el7        base                     51 k
 perl-PlRPC              noarch 0.2020-14.el7     base                     36 k

Transaction Summary
================================================================================
Install  2 Packages (+11 Dependent packages)

Total download size: 27 M
Installed size: 137 M
Downloading packages:
--------------------------------------------------------------------------------
Total                                              5.5 MB/s |  27 MB  00:04
Running transaction check
Running transaction test


Transaction check error:
  file /usr/lib64/mysql/plugin/dialog.so from install of mariadb-common-3:10.1.18-3.el7.x86_64 conflicts with file from package mariadb-libs-1:5.5.52-1.el7.x86_64
  file /usr/lib64/mysql/plugin/mysql_clear_password.so from install of mariadb-common-3:10.1.18-3.el7.x86_64 conflicts with file from package mariadb-libs-1:5.5.52-1.el7.x86_64

Error Summary
-------------


[ info ]   Checking if packages were installed correctly


[ warn ]   The following packages failed to install: mariadb mariadb-server


[ ERROR ]  Error during group or package installation, check the output for details.

           Press Enter to continue.


Cheers,
Cédric
