### ISSUE TITLE
TrinityX and CentOS 7.3

### ISSUE THREAD

**Issue by cedriccastagnede** [clustervision/trinityX#155]
Hello Guys, 

I do not know for sure if you will encounter this with CentOS 7.3 but luna need the following package into a compute image: kernel kernel-devel kernel-headers dracut dracut-network dracut-config-rescue dracut-config-generic tzdata rootfiles openssh openssh-server openssh-clients openssl openssl-libs nfs-utils tar nc wget curl rsync gawk sed gzip parted e2fsprogs ipmitool vim-enhanced vim-minimal grub2 deltarpm bind-utils

And you must write an empty file /etc/fstab into the image to be able to generate and deploy properly a compute image.

Cheers,
Cédric

**Comment by rispoli** [comment]
Confirm that:
```FIX for kernel >= 3.10.0-514.2.2.el7.x86_64

[root@loki ~]# yum --installroot=/trinity/images/openstack-compute -y install dracut-config-generic
[root@loki ~]# touch /trinity/images/openstack-compute/etc/fstab
```

works as discovered by Cédric here: http://kb/wp/index.php/openstack-installation-procedure-on-loki/
