### ISSUE TITLE
After controller reboot, second interface IP is gone

### ISSUE THREAD

**Issue by Marc69** [clustervision/trinityX#156]
Version: 2b36495 (release_10)
Environment: amaster1-controller01

Although it is configured to be assigned statically on boot, I have to add it manually.
Perhaps not very serious, still annoying for it makes slurm, dhcpd and dns resolution fail.
```
[root@amaster-controller1 controller]# cat /etc/sysconfig/network-scripts/ifcfg-eno2
TYPE=Ethernet
BOOTPROTO=static
IPV4_ADDR=10.39.255.254
PREFIX=16
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_PEERDNS=yes
IPV6_PEERROUTES=yes
IPV6_FAILURE_FATAL=no
NAME=eno2
UUID=db6256e7-21f0-49fc-a627-7fcc913ddb97
DEVICE=eno2
ONBOOT=yes
DNS=10.39.255.254
PEERDNS=no
NM_CONTROLLED=no
ZONE=trusted
```
Workaround:
ip a add 10.39.255.254/16 dev eno2; systemctl restart dhcpd; systemctl restart named

**Comment by heatherLstephens** [comment]
not reproducible
