### ISSUE TITLE
[master][openstack] DHCP lease in neutron

### ISSUE THREAD

**Issue by cedriccastagnede** [clustervision/trinityX#202]
Hello,
When you start booting/closing a bunch of VM instance, neutron dhcp do not lease IP though time.
We should uncomment dhcp_lease_duration parameter in neutron config file or set it with a reasonable value. 

[root@dell01 ~]# grep dhcp_lease_duration /etc/neutron/neutron.conf
dhcp_lease_duration = 86400

Cheers,
Cédric

**Comment by hicham-a** [comment]
Actually the `dhcp_lease_duration` option if undefined takes the value 86400 by default; We don't have to explicitly  set it unless a shorter lease time is desired.
