### ISSUE TITLE
fail2ban do not start during installer

### ISSUE THREAD

**Issue by cedriccastagnede** [clustervision/trinityX#209]
Hello,

During release_10.1 installation, fail2ban fails to start.
Directory /var/run/fail2ban MUST be created before starting the service.

Regards,
Cédric

**Comment by dchirikov** [comment]
Have not checked if it's reproducible, but my 2 cents.

`/var/run/` is actually tmpfs filesystem which will be recreated after boot:
```
$ ll /var/run
lrwxrwxrwx. 1 root root 6 Sep  7 18:16 /var/run -> ../run
$ mount | grep run
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
```
so we have 2 options
1. Wait for fix in upstream
2. 
```
cat <<EOF>/etc/systemd/system/fail2ban.service.d/preexec.conf
[Service]
ExecStartPre=-/usr/bin/mkdir /var/run/fail2ban
EOF
```

**Comment by cedriccastagnede** [comment]
For the record, i've got the error during UoN installation but not during framework cluster installation (the new rpmbuild server).

**Comment by Marc69** [comment]
I had that issue before, but not any more, so I figure Dmitry's option 1 has worked out.
To be sure, I have:
Source RPM  : fail2ban-0.9.6-3.el7.src.rpm
Build Date  : Wed 15 Feb 2017 07:38:33 PM CET
