### ISSUE TITLE
Slurm pam module missing on compute node / all users can access compute node all the time

### ISSUE THREAD

**Issue by cedriccastagnede** [clustervision/trinityX#211]
Hello Guys,

During compute image generation, you must add slurm-pam_slurm package in order to enable ssh between nodes for normal user only during allocation. 
You must also do:
cat << EOF >> /etc/pam.d/sshd
# Trinity - SLURM
account    required   pam_unix.so
account    required     pam_slurm.so
EOF 

Regards,
Cédric

**Comment by heatherLstephens** [comment]
implemented
