### ISSUE TITLE
OpenStack dashboard access 

### ISSUE THREAD

**Issue by cedriccastagnede** [clustervision/trinityX#213]
Hello,

In order to access to the dashboard, the following commands must be done:
$ sed -i 's|127.0.0.1|0.0.0.0|' /etc/sysconfig/memcached
$ systemctl restart memcached
$ systemctl restart httpd

Otherwise, you will get the following behavior:
![image](https://cloud.githubusercontent.com/assets/7941380/23612348/6f6b8cb4-027b-11e7-8833-b26ef3fcffc8.png)

**Comment by hicham-a** [comment]
Fixed in fc49b3a
