### ISSUE TITLE
Zabbix repo key doesn't fit any more

### ISSUE THREAD

**Issue by Marc69** [clustervision/trinityX#215]
Version: 08340aa
Environment: ha2-controller1

This happens in zabbix-agent.pkglist during compute image creation:
```
Dependencies Resolved

================================================================================
 Package              Arch           Version               Repository      Size
================================================================================
Installing:
 zabbix-agent         x86_64         3.2.4-2.el7           zabbix         342 k

Transaction Summary
================================================================================
Install  1 Package

Total size: 342 k
Installed size: 1.3 M
Downloading packages:
warning: /trinity/images/compute-2017-03-06-15-06/var/cache/yum/x86_64/7/zabbix/packages/zabbix-agent-3.2.4-2.el7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 79ea5ed4: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX


The GPG keys listed for the "Zabbix Official Repository - x86_64" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.


 Failing package is: zabbix-agent-3.2.4-2.el7.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX


[ info ]   Checking if packages were installed correctly


[ warn ]   The following packages failed to install: zabbix-agent


[ ERROR ]  Error during package installation


[ ERROR ]  Error during post script: zabbix-agent
```

PS: Apparently I'm not the first to meet with this: https://support.zabbix.com/browse/ZBX-11868

**Comment by cedriccastagnede** [comment]
Hello Guys,

I've got the issue several time. Why do not just install zabbix-release after adding the repo manually ?
[root@framework framework]$ yum info --installroot=/trinity/images/slurm-compute zabbix-release
Loaded plugins: fastestmirror, versionlock
Determining fastest mirrors
 * base: mirror.proserve.nl
 * elrepo: ftp.nluug.nl
 * epel: epel.mirror.wearetriple.com
 * extras: mirror.widexs.nl
 * updates: centos.mirror.transip.nl
OpenHPC                                                                                                   430/430
OpenHPC-updates                                                                                             67/67
zabbix                                                                                                      79/79
zabbix-non-supported                                                                                          4/4
Available Packages
Name        : zabbix-release
Arch        : noarch
Version     : 3.2
Release     : 1.el7
Size        : 13 k
Repo        : zabbix/x86_64
Summary     : Zabbix repository configuration
URL         : http://www.zabbix.com
License     : GPL
Description : This package contains the Zabbix official repository
            : GPG key as well as configuration for yum.

**Comment by dchirikov** [comment]
Confirmed. It's zabbix issue:
https://support.zabbix.com/browse/ZBX-11868
We are trying to fix it here 
c5c65b67d487a573ed8b7da05e55cb971989d7c6
and here
57aa5bc8d6e66a7488f315be105ab914f45e31f1

**Comment by heatherLstephens** [comment]
solved
