### ISSUE TITLE
obol doesn't show supplementary groups

### ISSUE THREAD

**Issue by ig0rmeister** [clustervision/trinityX#227]
[root@controller ~]# obol user show testuser2
{
    "cn": "testuser2", 
    "gidNumber": "1070", 
    "homeDirectory": "/trinity/home/testuser2", 
    "loginShell": "/bin/bash", 
    "shadowExpire": "-1", 
    "shadowLastChange": "17310", 
    "shadowMax": "99999", 
    "shadowMin": "0", 
    "shadowWarning": "7", 
    "sn": "testuser2", 
    "uid": "testuser2", 
    "uidNumber": "1070", 
    "userPassword": "passw0rd"
}

**Comment by msteggink** [comment]
Solved in obol2
