### ISSUE TITLE
additional packages - iperf3

### ISSUE THREAD

**Issue by ivryabtsev** [clustervision/trinityX#245]
Trinity installer tries to install iperf3 but it is not available in repos:

[ warn ]   The following packages failed to install: iperf3
[ ERROR ]  Error during package installation
[ ERROR ]  Error during post script: controller/additional-packages
          [R]etry, [C]ontinue or [E]xit? [R] r
 ----->>>  Installing packages: /trinityx/configuration/./controller/additional-packages.pkglist  <<<-----

[root@localhost ~]# yum install iperf3
Loaded plugins: fastestmirror, versionlock
clustervision-master-repo-1.0-tr17-extra                                           | 2.9 kB  00:00:00     
clustervision-master-repo-1.0-tr17-local                                           | 2.9 kB  00:00:00     
clustervision-master-repo-1.0-tr17-module                                          | 2.9 kB  00:00:00     
Loading mirror speeds from cached hostfile
 * base: ftp.nluug.nl
 * elrepo: ftp.nluug.nl
 * epel: ftp.nluug.nl
 * extras: centos.mirror.transip.nl
 * updates: mirror.denit.net
No package iperf3 available.

**Comment by Marc69** [comment]
Same here when I tried to configure a login image. Yet the package is there on my controller and my compute image (which were configured some time ago). Apparently yum can't access the luna repo:

[root@tmaster2-controller01 testing]# chroot /trinity/images/login-2017-08-18-14-56
[root@tmaster2-controller01 /]# yum repolist |grep -C1 luna
file:///trinity/shared/packages/luna/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /trinity/shared/packages/luna/repodata/repomd.xml"
Trying other mirror.
file:///trinity/shared/packages/luna/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /trinity/shared/packages/luna/repodata/repomd.xml"
Trying other mirror.
file:///trinity/shared/packages/pacemaker/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /trinity/shared/packages/pacemaker/repodata/repomd.xml"
Trying other mirror.
extras/7/x86_64                           CentOS-7 - Extras                  450
luna-local                                Luna - local repository              0
mariadb                                   MariaDB                             16

**Comment by dchirikov** [comment]
seems like iperf3 is not available in EPEL anymore
https://src.fedoraproject.org/rpms/iperf3/c/73a0b54d184aa3a8f0424c6c7838b3b3dfe3f8f8?branch=epel7

**Comment by hicham-a** [comment]
iperf3 is now part of the base centos repo.
