### ISSUE TITLE
image creation does not respect NODE_INITIAL_RPM if not the latest

### ISSUE THREAD

**Issue by cedriccastagnede** [clustervision/trinityX#258]
Hello,

When I create a compute image specifying the NODE_INITIAL_RPM to CentOS 7.3, the result is that I get a CentOS 7.4. 
A working fix can be done as following : 
[root@framework configuration]$ diff images/image-create.sh images/image-create.sh.bak
87,98d86
< if flag_is_set NODE_INITIAL_RPM ; then
<     echo_info 'Fix the release for the RPM dabatase in the target directory'
<     ver=$(echo ${NODE_INITIAL_RPM}|cut -d"-" -f3-4 --output-delimiter="."|cut -d. -f1-3)
<     mkdir -p "${TARGET}/etc/yum/vars/"
<     echo "$ver" > "${TARGET}/etc/yum/vars/releasever"
<     sed -i "s|mirrorlist|#mirrorlist|" ${TARGET}/etc/yum.repos.d/CentOS*repo
<     sed -i "s|#baseurl|baseurl|"       ${TARGET}/etc/yum.repos.d/CentOS*repo
< fi
<
<
< #---------------------------------------
<

Of course, this fix is probably not generic enough.

Regards,
Cédric

**Comment by heatherLstephens** [comment]
not applicable anymore
