### ISSUE TITLE
UserKnownHostsFile setting in ssh_config

### ISSUE THREAD

**Issue by quentinleburel** [clustervision/trinityX#293]
Two bugs/features in one:

- in `roles/trinity/ssh/tasks/main.yml`, "Update ssh and sshd configuration files" isnt doing what it's supposed to be doing. Using "file" module is only setting file attributes, we should use the "copy" module if we want to copy the ssh{,d}_config files. This only affects the controllers, for node images we use "blockinfile" module and it works as expected.

- on the other hand, do we really want to have `UserKnownHostsFile /dev/null` in ssh_config ? It's polluting user jobs output with multiple `Warning: Permanently added 'lm3-w048' (ECDSA) to the list of known hosts.` lines for every ssh connection. Why don't we keep the default here ?

**Comment by hi-a** [comment]
We use `UserKnownHostsFile /dev/null` to prevent sshd from prompting for confirmation each time a new job is submitted. I'm not sure this is required though.

**Comment by quentinleburel** [comment]
`    StrictHostKeyChecking no` is what prevents sshd from prompting for confirmation:

```
     StrictHostKeyChecking
             If this flag is set to “yes”, ssh(1) will never automatically add host keys to the ~/.ssh/known_hosts file, and refuses to connect to hosts whose host key has changed.  This provides maximum protection against trojan
             horse attacks, though it can be annoying when the /etc/ssh/ssh_known_hosts file is poorly maintained or when connections to new hosts are frequently made.  This option forces the user to manually add all new hosts.  If
             this flag is set to “no”, ssh will automatically add new host keys to the user known hosts files.  If this flag is set to “ask”, new host keys will be added to the user known host files only after the user has con‐
             firmed that is what they really want to do, and ssh will refuse to connect to hosts whose host key has changed.  The host keys of known hosts will be verified automatically in all cases.  The argument must be “yes”,
             “no”, or “ask”.  The default is “ask”.
```

UserKnownHostsFile /dev/null is a legacy from TrinityCE iirc. sshd host keys used to be recreated at every boot of compute nodes, so they would change all the time. Nowadays the host key is stored in the image, so storing them in the default location `.ssh/known_hosts` should be fine ?
