### ISSUE TITLE
CentOS image creation on RHEL

### ISSUE THREAD

**Issue by kostty** [clustervision/trinityX#318]
From Pieter:
> creating a centos image did not work, was failing on installing the packages. Fixed after:
> ```
>/etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
>-----BEGIN PGP PUBLIC KEY BLOCK-----
>Version: GnuPG v1.4.5 (GNU/Linux)
>...
>-----END PGP PUBLIC KEY BLOCK-----
>
>gpg --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
>```

**Comment by heatherLstephens** [comment]
now working
