### ISSUE TITLE
release life cycle

### ISSUE THREAD

**Issue by grafoo** [clustervision/trinityX#339]
hi!
can you describe how the release life cycle of TrinityX will look like for future releases?
i'm also interested in the code quality of the branches. is the master branch considered stable and the one where pull requests should be based on?

cheers,
manuel

**Comment by heatherLstephens** [comment]
Hi Manuel,

Glad to hear of your interest in TrinityX!

Typically we release 2-3x per year. Our latest release, R11, was completed a couple months ago.

The master branch is stable, but it is best to base pull requests on the development branch as that's the one we use for development work. We then merge all to master when preparing for a release.

Let us know if you have any other questions or feedback.


Best wishes,
Heather

**Comment by aphmschonewille** [comment]
Item closed as being outdated with current release
