### ISSUE TITLE
Typo in release notes for Release 11

### ISSUE THREAD

**Issue by linuxstudio** [clustervision/trinityX#356]
I believe the link in the following text is not correct:

"Updated documentation at http://trinity-docs/docs/"

It appears in the release notes for Release 11

**Comment by kostty** [comment]
Hi Francesco, 

long time no see :) Thanks for the feedback!

The link you mentioned is indeed not reachable from the outside, as the server it refers to is on our intranet. We do plan to host a public version of the documentation as well, once that is done, the link will be updated to point to it.
