### ISSUE TITLE
SELINUX error

### ISSUE THREAD

**Issue by atulyadavtech** [clustervision/trinityX#375]
Hi Support,

The steps are executed as per the installation doc.
tested with "r12.0u1.tar.gz" and "r12.0u2.tar.gz"
CentOS Linux release 7.9.2009 (Core)

bash prepare.sh
ansible-playbook controller.yml -e ansible_python_interpreter=/usr/bin/python -v

But getting below mention error.
"fatal: [controller1]: FAILED! => {"changed": false, "msg": "SELinux is disabled on this host."}"

Thank You
Atul Yadav
Locuz

**Comment by msteggink** [comment]
Hi, Thank you for your interest. It is not designed to run SELinux disabled (as per message). You need to enable permissive mode (not enforcing).
