### ISSUE TITLE
No ubuntu at all?

### ISSUE THREAD

**Issue by surak** [clustervision/trinityX#385]
Hey,

second time I try it, after ISC. I get this on a clean ubuntu 23.04 server:

![Screenshot 2023-05-27 at 14 35 00](https://github.com/clustervision/trinityX/assets/878399/596d0cde-036b-4f72-8c79-e0bd027848ba)

looking at the code and docu, I don't see much mention to anything debian/ubuntu at all either.

Any pointers?

**Comment by AlexNinaber** [comment]
Hi Surak - apologies, this is the (very) old version of TrinityX, the new version based on Python 3 with Rocky 9 (etc) support will be publicly released in the next 3 months. Ubuntu client support will be released at the same time.

**Comment by surak** [comment]
Thanks. Would it make sense to update the readme, so people won’t get mistakenly disappointed? Given you promoted the software on ISC….

**Comment by AlexNinaber** [comment]
Yes good point, I've changed the text.

**Comment by Qiangong2** [comment]
Hi @AlexNinaber, is there any update on when the new version will be publicly released?

**Comment by msteggink** [comment]
Hi @Qiangong2 , we just pushed a new release. We now support EL8/EL9 and Ubuntu (22).

**Comment by Qiangong2** [comment]
Thanks for the update @msteggink! However, I notice that the docs site your pdf points to (https://docs.clustervision.com/), does not work.

I'm getting a "DNS_PROBE_FINISHED_NXDOMAIN" error, so maybe your firewall is blocking external access?

**Comment by surak** [comment]
It seems like there's something I am missing while following the readme, then: 

![Screenshot 2023-10-13 at 16 04 31](https://github.com/clustervision/trinityX/assets/878399/55fdb896-05f7-43b6-a586-586fbc1d973a)

**Comment by brunopereira81** [comment]
If I read the initial setup steps, its seems that for the controllers you need a RHEL based OS. Ubuntu shows listed for the compute nodes only.

Seems like you are using Ubuntu for the controller initial setup, correct?

**Comment by surak** [comment]
That's what I understand as well, but that's not clear from what's documented. 

I would avoid having a controller/login node on a different OS than the computes, as users would compile stuff on the logins and I would end up with way more trouble than it's worth

**Comment by brunopereira81** [comment]
Yes, but a login node is not a control node, should not be in most cases at least, for several reasons.

A login node should probably be closer to a compute, so the design is quite ok here. Just deploy the control nodes w any RHEL base and any client nodes w Ubuntu?

**Comment by msteggink** [comment]
Yes, the controller node only supports Enterprise Linux for now. @brunopereira81  is correct, the compute supports both EL and Ubuntu.

**Comment by surak** [comment]
When you say "for now", is there any plans for this to change?

**Comment by dmantione** [comment]
It is being looked into, but I'd say it is much important to work on the ability that users can request their favourite distribution through Slurm, than the distribution that runs on the master node.
