### ISSUE TITLE
named listens on all interfaces (internal and external)

### ISSUE THREAD

**Issue by alainvanhoof** [clustervision/trinityX#391]
named should only listen for DNS queries on the internal interface, the following sets it to listen on all (any) interface:

site/roles/trinity/bind/tasks/main.yml

- name: Configure named to listen on all ports
  replace:
    path: /etc/named.conf
    regexp: "{{ item }}"
    replace: " any; "
  with_items:
    - ' localhost; '
    - ' 127\.0\.0\.1; '
    - ' ::1; '
  notify: restart named

sugestion is to replace "any" with {{ trix_ctrl1_ip }} for example

**Comment by alainvanhoof** [comment]
As nmed also need to listen on 127.0.0.1 ->
{{ trix_ctrl1_ip }};127.0.0.1;

**Comment by aphmschonewille** [comment]
True. named listens on every interface/ip. we use the firewall to limit access from outside the cluster.
Limiting the interfaces might have adverse effects where more internal networks are created at a later stage and or the use of floating IPs not being included (H/A).

**Comment by aphmschonewille** [comment]
There is a way to manually configure this by changing the template:
edit /trinity/local/luna/daemon/templates/templ_dns_conf.cfg  and then restart the daemon (luna2-daemon).

**Comment by alainvanhoof** [comment]
The firewall is indeed blocking the access from the external interface. Thanks for pointing to the location of the template in the luna2-daemon repo that could set it when wanted. I tried to do it with the ansible script, but indeed it was changed back bij the daemon because of the template.
