### ISSUE TITLE
Issue regarding prepare.sh, ansible and matching python version

### ISSUE THREAD

**Issue by xdkreij** [clustervision/trinityX#392]
When following the documentation @docs.clustervision.com and here on git.

./prepare.sh states it cannot find and install python3.11

This is reasonable because py3.11 needs RHEL +8.8 or +9.2
(redhat docs -> Python 3.11 can only be installed from RHEL 8.8 and RHEL 9.2 release)

**Running OS Version**
`Red Hat Enterprise Linux release 8.6 (Ootpa)`

**Issue prepare.sh**
`Error:
 Problem: cannot install the best candidate for the job
  - nothing provides /usr/bin/python3.11 needed by ansible-8.3.0-1.el8.noarch
  - nothing provides python(abi) = 3.11 needed by ansible-8.3.0-1.el8.noarch
  - nothing provides python3.11dist(ansible-core) >= 2.15.3 needed by ansible-8.3.0-1.el8.noarch`

**Expected results**
- prepare.sh to verify which RHEL version is running, and install matching ansible and python compatible versions accordingly
   prepare.sh: -> `yum install curl tar **ansible** git epel-release -y`
- prepare.sh to finish run successfully
- documentation to provide minimum ansible and python versions required based on OS version

**Comment by msteggink** [comment]
```
Error:
 Problem: cannot install the best update candidate for package ansible-7.2.0-1.el8.noarch
  - nothing provides python3.11dist(ansible-core) >= 2.15.3 needed by ansible-8.3.0-1.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[root@localhost ~]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.7 (Ootpa)
```

Ansible itself is trying to install 3.11

**Comment by xdkreij** [comment]
That's correct, because prepare.sh is always installing the latest ansible version and expects al its dependencies are reachable as well
There's zero control over OS/Package compatibilities this way, no insurance of a working ansible setup. Unless perpare.sh somehow verifies if certain minimally required module versions are enabled and installed `yum module list | grep python` && `yum module enable <module_name>` and matches that against the ansible version to be installed.

![image](https://github.com/clustervision/trinityX/assets/24566213/274fb9fa-3242-434d-ac5f-7a1ddfcf0f33)


Also, it's advised to install ansible using pip (python) over yum. Pip should avoid the issue because the python package manager will install the latest compatible version of Ansible that `this` python version _can_ run, which is not always the latest or equal to the package provided via yum.

To quote: 
`'Installing python packages via yum is generally discouraged unless there is some sort of native dependency.
Using pip or even better, a virtualenv is advised for both compatibility as well as from a security perspective
 
e..g create a dedicated ansible user on the host, log in as ansible and  'pip install ansible **--user**'` 

The above provides a 2-for-1 benefit, as RHEL9 has root disabled by default (avoid sudo su, always use sudo)
and one cannot assume root access is available.


This makes anything less than RHEL8.8 and python3.11 incompatible with the prepare.sh script.

**Comment by xdkreij** [comment]
fyi: https://github.com/wazuh/wazuh-ansible/issues/967
