### ISSUE TITLE
SELinux | prepare.sh vs ansible

### ISSUE THREAD

**Issue by xdkreij** [clustervision/trinityX#393]
**prepare.sh selinux config**
` # To disable SElinux on the controller node
  setenforce 0
  sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config
`

**Error running ansible-playbook controller.yml**
`TASK [trinity/bind : Selinux fcontext on files] ****************************************************************************************************
fatal: [d-vcpu-srv-01]: FAILED! => {"changed": false, "msg": "SELinux is disabled on this host."}
`

**Expected results**
- prepare.sh to re-enable selinux again and reboot host (to re-enable selinux)
- AND ansible role to verify if SELinux is enabled & enable it first when it is not

**Comment by msteggink** [comment]
Yes, this is due to the fact you can't go from disabled to permissive without a reboot. The software only supports permissive and enforced is being planned. We will discuss internally how to address this.

**Comment by xdkreij** [comment]
> Yes, this is due to the fact you can't go from disabled to permissive without a reboot. The software only supports permissive and enforced is being planned. We will discuss internally how to address this.

It's an easy workaround of course; But in theory, SELinux shouldn't  have to be disabled in the first place (most ideal solution)
