### ISSUE TITLE
SLURM filepath issue

### ISSUE THREAD

**Issue by xdkreij** [clustervision/trinityX#394]
Changed path of trinity/shared to its own filesystem e.g. /trinity_shared as suggested in the documentation
within the all.yml file @group_vars

regardless, the service does not start due to issue in finding balance.sh @ the wrong location

I think the `trix_shared` variable isn't being used there, hence it's reverting back to default /trinity/shared location instead

```
[2023-12-15T14:28:07.663] slurmctld version 22.05.2 started on cluster cluster
[2023-12-15T14:28:07.672] error: Invalid EpilogSlurmctld(`/trinity/shared/etc/slurm/balance.sh`): No such file or directory
[2023-12-15T14:28:07.674] error: slurm_persist_conn_open_without_init: failed to open persistent connection to host:d-vcpu-srv-01:6819: Connection refused
[2023-12-15T14:28:07.674] error: Sending PersistInit msg: Connection refused
```

Visiting the right config files @slurm role, we can see the path is set statically

```
cat roles/trinity/slurm/files/slurm-user.conf
PriorityType=priority/multifactor
PriorityWeightQOS=10000  # All weights are mutiplied by a value between 0 and 1 and then converted back to a 32 bit unsigned int so make them all big enough not to lose precision
JobAcctGatherFrequency=15
JobAcctGatherType=jobacct_gather/linux
PreemptType=preempt/none

# Timers
SlurmctldTimeout=10
SlurmdTimeout=10

# Consumable Resource
Proctracktype=proctrack/cgroup
#FastSchedule=0
SelectType=select/cons_res
SelectTypeParameters=CR_Core
DefMemPerCPU=1024


PropagateResourceLimitsExcept=MEMLOCK

TaskProlog=/trinity/shared/etc/slurm/prolog.sh
Prolog=/trinity/shared/etc/slurm/prolog.sh
Epilog=/trinity/shared/etc/slurm/epilog.sh
EpilogSlurmCtld=/trinity/shared/etc/slurm/balance.sh
```

**Expected results**
- the slurm services to start without issues
- variables set @ correct config files (move them to templates instead of files); Currently this breaks the suggestion to use separate filesystems

**Comment by msteggink** [comment]
The integration of SLURM isn't that far yet, and there are paths which are still dependent on a (hardcoded) /trinity path.

**Comment by xdkreij** [comment]
> The integration of SLURM isn't that far yet, and there are paths which are still dependent on a (hardcoded) /trinity path.

Shouldn't be to difficult to move the .conf files to a j2 template ;-)

**Comment by msteggink** [comment]
> Shouldn't be to difficult to move the .conf files to a j2 template i guess ;-)

Indeed, we are doing that. The integration after installation isn't there yet.

> Otherwise the suggestion to move trinity to dedicated partitions (lvm) is not applicable, and the docs should be updated accordingly

> imho - only state functionalities that are fully tested and completed, within the docs; If it's not completed yet, don't advice it or move the configuration advisory to 'functionalities that are planned for future releases'

You are completely right. We put it in a variable but don't fully offer to change it (some components are relying on the default paths), so there is only the illusion of choice regarding the alternative tree path. Ultimately it would be best that it would be configurable but we are not there yet.

**Comment by xdkreij** [comment]
> > Shouldn't be to difficult to move the .conf files to a j2 template i guess ;-)
> 
> Indeed, we are doing that. The integration after installation isn't there yet.
> 
> > Otherwise the suggestion to move trinity to dedicated partitions (lvm) is not applicable, and the docs should be updated accordingly
> 
> > imho - only state functionalities that are fully tested and completed, within the docs; If it's not completed yet, don't advice it or move the configuration advisory to 'functionalities that are planned for future releases'
> 
> You are completely right. We put it in a variable but don't fully offer to change it (some components are relying on the default paths), so there is only the illusion of choice regarding the alternative tree path. Ultimately it would be best that it would be configurable but we are not there yet.

I've reconfigured the test server to use a single lvm (/trinity) instead. Curious how far that will get me for now :-)

**Comment by bartlamboo** [comment]
> > The integration of SLURM isn't that far yet, and there are paths which are still dependent on a (hardcoded) /trinity path.
> 
> Shouldn't be to difficult to move the .conf files to a j2 template i guess ;-)
> 
> Otherwise the suggestion to move trinity to dedicated partitions (lvm) is not applicable, and the docs should be updated accordingly
> 
> imho - only state functionalities that are fully tested and completed, within the docs; If it's not completed yet, don't advice it or move the configuration advisory to 'functionalities that are planned for future releases'
> 
> my 2 cents

Keep in mind that the recommendation to use dedicated partitions still stands. 
But so far all work was done while mounting the newly created LVM partitions to their old paths.
So similar to the below fstab example.

```
/dev/mapper/rl-trinity-shared /trinity/shared                    xfs    defaults        0 0
/dev/mapper/rl-trinity-images /trinity/images                    xfs    defaults        0 0
```
