### ISSUE TITLE
Ubuntu 20 support

### ISSUE THREAD

**Issue by msteggink** [clustervision/trinityX#407]
When running a playbook, to use Ubuntu 20 (Focal Fossa)

Change the Jammy (24) to Focal: trinityX/site/roles/trinity/image-create-ubuntu/defaults/main.yml
```
9c9
< ubuntu_distribution_release: focal
---
> ubuntu_distribution_release: jammy
```

However the role isnt prepared for this. The only fix required:
```
TASK [trinity/prometheus-ipmi-exporter : Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.] ***
fatal: [ubuntu.osimages.luna]: FAILED! => {"msg": "No file was found when using first_found."}
```

The missing file is Ubuntu20.yaml: site/roles/trinity/prometheus-ipmi-exporter/vars/
A simple copy will solve it.
`cp Ubuntu22.yaml Ubuntu20.yaml`

**Comment by aphmschonewille** [comment]
done.
