### ISSUE TITLE
Check image_name earlier in playbook/role

### ISSUE THREAD

**Issue by mulderij** [clustervision/trinityX#410]
When providing the image_name var with the playbook compute-redhat.yml (and probably also compute-ubuntu.yml) the existence of the image is first checked on line 231 of [site/roles/trinity/image-create-redhat/tasks/main.yml](https://github.com/clustervision/trinityX/blob/6cc431327813de1c80016765d75203585704ecd2/site/roles/trinity/image-create-redhat/tasks/main.yml) with:
```
- name: Verify if image already exists in luna
  shell: "luna osimage show {{ image_name }}"
  register: redhat_image_in_luna
  ignore_errors: true
```
Since this code indirectly also checks the naming convention of image_name (through an error from luna) an unusable image_name could have been detected earlier in the playbook or role to avoid running time consuming tasks only to discover the image_name is not excepted.
The issue is reproducible by running (underscore is not allowed):
`ansible-playbook compute-redhat.yml --extra-vars 'image_name=default_rhel9'`

**Comment by aphmschonewille** [comment]
Hi. thanks for letting this know. Yes now in hindsight this could have been solved in a better way. Note that i have refactored the luna daemon code to allow less strict names (allowing cpas, spaces, etc) for anything non node, switch, network and otherdevice related names. This code will become available soon and i will look into making the ansible part a bit smarter.
-Antoine

**Comment by aphmschonewille** [comment]
The next push contains a check for osimage name. It will check the name first thing before ansible continues.

**Comment by aphmschonewille** [comment]
It's pushed. Current release will check the image name before proceeding.
