### ISSUE TITLE
AttributeError: module 'luna' has no attribute 'on_starting'

### ISSUE THREAD

**Issue by psantana5** [clustervision/trinityX#412]
Good afternoon,

When setting up TrinityX in Rocky Linux 8.5, we encounter this error.
```
AttributeError: module 'luna' has no attribute 'on_starting'
``` 
When we launch the Ansible playbook, we get stuck on the task that sets up the DNS forwarders for TrinityX. It looks for _https://example:7050/version_ but the daemon does not start due to this error and therefore nothing is listening on port 7050.  

This error is located in the **gunicorn.py** file in the daemon configuration folder. Note that there is an import in the gunicorn.py file where it does try to import a module named "luna".

Has anybody else encountered this issue and if so, what solutions do you offer?

Thank you.

**Comment by psantana5** [comment]
Hello, I have got an update on this issue. After moving the luna.py file inside the config/  directory, it seems that Python does find those properties. However, now I get this error:

`Got this back from db_status: 200 {'driver': 'SQLite3', 'database': '/trinity/local/luna/daemon/common/luna.db', 'read': True, 'write': True}
Failed to read config file: /trinity/local/luna/daemon/config/gunicorn.py
Traceback (most recent call last):
  File "/trinity/local/python/lib64/python3.9/site-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/trinity/local/luna/daemon/config/gunicorn.py", line 6, in <module>
    import luna
  File "/trinity/local/luna/daemon/luna.py", line 44, in <module>
    from utils.housekeeper import Housekeeper
  File "/trinity/local/luna/daemon/utils/housekeeper.py", line 73
    match first:
          ^
SyntaxError: invalid syntax`

**Comment by aphmschonewille** [comment]
What is also helpful is looking inside the systemd service, as there you can find how we start the daemon.
-A
