### ISSUE TITLE
ERROR :: Unable to reach https://trinityx:7050/version Try again or check the config.

### ISSUE THREAD

**Issue by psantana5** [clustervision/trinityX#413]
Good morning,

I'm experiencing issues with the Luna daemon. I encounter an error when I use the cURL command with "trinityx" as the hostname. However, using "127.0.0.1" instead works correctly. Here's the command and the respective outputs:

```
curl -k https://trinityx:7050/version
curl: (6) Could not resolve host: trinityx
curl -k https://127.0.0.1:7050/version
{"version": {"api": 1, "commit": "711e3a5---DUMMY---278ad6399b", "luna": "2.0.0001"}}
```

I attempted to resolve the issue by modifying the Gunicorn configuration file to use "127.0.0.1" for the API. Despite making this change and restarting the service, the problem persists. The service still fails to resolve the "trinityx" hostname and the API is still located in trinityx.

Could you guide me on how I can **properly** change the configuration so the Luna daemon points at 127.0.0.1 instead of _trinityx_?

Thank you.

**Comment by aphmschonewille** [comment]
Hi there.

i assume that trinityx as hostname does not resolve. can you try: `host trinityx`?
if that doesn't work, you could add the following block to /etc/hosts if it does not exist yet?:
`<controller ip>     trinityx`
or add trinityx to the line where it says 127.0.0.1 or the controller ip

**Comment by psantana5** [comment]
Fixed, thank you very much! I
