### ISSUE TITLE
efi tools for Ubuntu

### ISSUE THREAD

**Issue by msteggink** [clustervision/trinityX#414]
Could you add the following to the default Ubuntu to support efi/uefi diskful setups?
Package:

- dosfstools
- efibootmgr

And for the luna2-client: luna hooks (`/usr/share/initramfs-tools/hooks/luna`):

```
copy_exec /usr/sbin/mkfs.ext4 /usr/sbin
copy_exec /usr/sbin/mkfs.xfs /usr/sbin
copy_exec /usr/sbin/mkfs.vfat /usr/sbin
copy_exec /usr/sbin/parted /usr/sbin
copy_exec /usr/bin/efibootmgr /usr/bin
```

**Comment by aphmschonewille** [comment]
it'll be added in next push
