### ISSUE TITLE
slurmd may not start always

### ISSUE THREAD

**Issue by msteggink** [clustervision/trinityX#416]
I've observed with Ubuntu that it tries to start slurmd configless (since no valid slurm.conf was yet found). This may be due to some race condition but slurmd gives up on the file and tries to query DNS for the slurmctld record, which is not the default on most clusters.

```
Jun 04 07:47:48 server slurmd[1011]: slurmd: error: fetch_config: DNS SRV lookup failed
Jun 04 07:47:48 server slurmd[1011]: slurmd: error: _establish_configuration: failed to load configs
Jun 04 07:47:48 server  slurmd[1011]: slurmd: error: slurmd initialization failed
Jun 04 07:47:48 server slurmd[1011]: error: resolve_ctls_from_dns_srv: res_nsearch error: Unknown host
Jun 04 07:47:48 server slurmd[1011]: error: fetch_config: DNS SRV lookup failed
Jun 04 07:47:48 server slurmd[1011]: error: _establish_configuration: failed to load configs
Jun 04 07:47:48 server slurmd[1011]: error: slurmd initialization failed
```

Adding a config parameter will force the daemon to keep retrying until it can find a file:
```
# cat  /etc/default/slurmd
SLURMD_OPTIONS="-f /etc/slurm/slurm.conf"
```

On new boot:
```
Jun 04 08:04:31 server slurmd[1011]: error: s_p_parse_file: cannot stat file /etc/slurm/slurm.conf: No such file or directory, retrying in 1sec up to 60sec
```

**Comment by aphmschonewille** [comment]
Unfortunately we do not install slurm inside the ubuntu image as we're leaning, because of version compatibility, mostly on openhpc slurm packages. There is no ubuntu repo for openhpc. Adding this file is therefor meaningless inside the ubuntu image.
