### ISSUE TITLE
/proc is not mounted this is not a suppored mode of operation - when provisioning nodes

### ISSUE THREAD

**Issue by trick-1** [clustervision/trinityX#421]
I have just stood up a new environment

Controller: Rocky Linux 9.4
Installed trinityX as per instructions

When I provision nodes using an image generated from the compute-default.yml image they fail. Reviewing the journalctl -xe on the node I see the following. 
<img width="1107" alt="image" src="https://github.com/clustervision/trinityX/assets/8552368/c2d0d9c2-9f88-4e24-8bcc-872cd111f0f2">

Appreciate suggestions or insight.

Regards

Richard

**Comment by trick-1** [comment]
further to this sysroot mount fails as follows
<img width="1120" alt="image" src="https://github.com/clustervision/trinityX/assets/8552368/59397f1a-8ca0-41aa-a8b9-19407fd76aba">

**Comment by aphmschonewille** [comment]
could you supply me with the following information please:
- luna node show node001 -R
- luna group show compute -R
- the playbook you used to create the image
- the last 2 lines of group_vars/all.yml
- from the node itself at current stage, all files in /lunatmp (if it exists still)
thanks!
-A

**Comment by trick-1** [comment]
[root@trinityx ejb]# luna node show node001 -R
{
  "name": "node001",
  "kerneloptions": null,
  "switchport": null,
  "service": false,
  "setupbmc": true,
  "status": "Luna installer: success",
  "comment": null,
  "roles": "None",
  "vendor": "QEMU",
  "assettag": "Not Specified",
  "prescript": "",
  "partscript": "mount -t tmpfs tmpfs /sysroot\r\n",
  "postscript": "echo 'tmpfs / tmpfs defaults 0 0' >> /sysroot/etc/fs
  "netboot": "True",
  "localinstall": "False",
  "bootmenu": "False",
  "provision_interface": "BOOTIF",
  "provision_method": "torrent",
  "provision_fallback": "http",
  "tpm_uuid": null,
  "tpm_pubkey": null,
  "tpm_sha256": null,
  "unmanaged_bmc_users": null,
  "group": "compute",
  "osimage": "compute",
  "osimage_source": "group",
  "bmcsetup": "compute",
  "bmcsetup_source": "group",
  "osimagetag": "computeimage",
  "osimagetag_source": "group",
  "switch": null,
  "setupbmc_source": "group",
  "netboot_source": "group",
  "localinstall_source": "default",
  "bootmenu_source": "default",
  "roles_source": "default",
  "provision_method_source": "cluster",
  "provision_fallback_source": "cluster",
  "provision_interface_source": "default",
  "prescript_source": "default",
  "partscript_source": "group",
  "postscript_source": "group",
  "hostname": "node001.trix",
  "interfaces": [
    {
      "interface": "BOOTIF",
      "ipaddress": "10.141.0.1",
      "macaddress": "bc:24:11:7e:b7:3b",
      "network": "trix"
    },
    {
      "interface": "BMC",
      "ipaddress": "10.148.0.1",
      "macaddress": null,
      "network": "ipmi"
    }
  ]
}
[root@trinityx ejb]# luna group show compute -R
{
  "name": "compute",
  "setupbmc": "True",
  "domain": "cluster",
  "kerneloptions": null,
  "prescript": "",
  "partscript": "mount -t tmpfs tmpfs /sysroot\r\n",
  "postscript": "echo 'tmpfs / tmpfs defaults 0 0' >> /sysroot/etc/fs
  "netboot": "True",
  "localinstall": "False",
  "bootmenu": "False",
  "comment": "",
  "roles": null,
  "provision_interface": "BOOTIF",
  "provision_method": "torrent",
  "provision_fallback": "http",
  "unmanaged_bmc_users": "",
  "interfaces": [
    {
      "interface": "BOOTIF",
      "network": "trix"
    },
    {
      "interface": "BMC",
      "network": "ipmi"
    }
  ],
  "setupbmc_source": "group",
  "netboot_source": "group",
  "localinstall_source": "default",
  "bootmenu_source": "default",
  "provision_interface_source": "default",
  "provision_method_source": "cluster",
  "provision_fallback_source": "cluster",
  "prescript_source": "default",
  "partscript_source": "group",
  "postscript_source": "group",
  "osimage": "compute",
  "bmcsetupname": "compute",
  "osimagetag": "computeimage",
  "osimage_source": "group",
  "bmcsetupname_source": "group",
  "osimagetag_source": "group"
}


-----PlayBook-----
[root@trinityx site]# more compute-default.yml 
---
- hosts: localhost
  pre_tasks:
  #
  # the image name can be set in the below fact.
  #
  - name: Set image name
    set_fact:
      image_name: "compute"

- import_playbook: imports/trinity-redhat-image-create.yml
  vars:
    image_name: "{{ hostvars['localhost']['image_name'] }}"
    # The password to set up for the root user in the image.
    # If empty, it will be generated at random.
    #
    image_password:
    #
    # Alternative distribution build. Supported are Rocky + Centos, v
ersion 8, 9, 8.9, 9.3
    # or any docker image, e.g. rockylinux:8
    alternative_distribution: Rocky-9.4
    # 
    # The alternative source can be 'base' or 'docker'
    #alternative_image_source: 'base'

- import_playbook: imports/trinity-redhat-image-setup.yml
  vars:
    hostlist: "{{ hostvars['localhost']['image_name'] }}.osimages.lun
a"

- hosts:
    - "{{ hostvars['localhost']['image_name'] }}.osimages.luna"
  roles:
    - role: trinity/wrapup-images
      tags: wrapup-images


- hosts: controllers
  roles:
    - role: trinity/pack-images
      vars:
         params:
            image_name: "{{ hostvars['localhost']['image_name'] }}"
      tags: pack-images

---last 4 lines of group-vars/all.yml--

trix_version: "14.1"
workload_manager: slurm

# DO NOT REMOVE: yml check: 140103
--- file set ----
I need to work out a way to get the files off the node....

**Comment by trick-1** [comment]
OK so I rebuilt my cluster using these instructions (the ones in the github just kept creating the same issue) and I have moved on. https://supercomputing.tue.nl/documentation/administration/trinityx/installation/
