### ISSUE TITLE
Rocky 8 image creation is missing slurm-slurmd package

### ISSUE THREAD

**Issue by mulderij** [clustervision/trinityX#425]
Rocky 8 image creation (and possible more) using playbook compute-default.yml (0a84779) is missing package `slurm-slurmd` when not installing OpenHPC. The installation uses {{ slurm_packages }} from site/roles/trinity/slurm/defaults/main.yml c8987aa.

(Also a compute image shouldn't need slurmctld and slurmdbd)

**Comment by aphmschonewille** [comment]
true. the way we install the image overlaps with the packages on the controller. will look into that as well as the missing package.
