### ISSUE TITLE
Rocky 8 image creation is not enabling powertools

### ISSUE THREAD

**Issue by mulderij** [clustervision/trinityX#426]
Rocky 8 image creation (and possible more) using playbook compute-default.yml (https://github.com/clustervision/trinityX/commit/0a847796949ab0645e8a194a9beda21b67258da1) is not enabling powertools repo (at least when not installing OpenHPC). The repo is installed, but not permanently enabled or temporarily enabled to install specific packages.

This repo is (at least) needed for:
hwloc-devel
libaec
lua-filesystem
lua-posix
perl-IO-Tty
perl-IPC-Run

**Comment by aphmschonewille** [comment]
True. will fix.
