### ISSUE TITLE
AlmaLinux9, installation failed multiple times at the same "TASK [trinity/image-create : Verify build]" for Ubuntu 

### ISSUE THREAD

**Issue by jjksaji** [clustervision/trinityX#432]
Dear All, 
I am using AlmaLinux 9 , doing the setup today 4 time for the latest version, each of this try the setup gets failed during the 
TASK [trinity/image-create : Verify build] 

the display message I am pasting here
TASK [trinity/image-create : Verify build] *********************************************************************************************************************************************
fatal: [controller1]: FAILED! => {"changed": false, "msg": "Ubuntu basic image build failed. please rerun playbook or look at /tmp/debootstrap.log"}

the log shows 

[root@controller1 trinityX]# cat /tmp/debootstrap.log
I: Checking Release signature
E: Release signed by unknown key (key id 871920D1991BC93C)
   **The specified keyring /usr/share/keyrings/ubuntu-archive-removed-keys.gpg may be incorrect or out of date.
   You can find the latest Debian release key at https://ftp-master.debian.org/keys.htm**l

Since it was repating multiple installation times the same message, I thought I will give the feedback here 
thanks 
Joseph John

**Comment by jjksaji** [comment]
I found the file  "/var/log/trinity.log "
I am uploading the log file 
[trinity.log](https://github.com/user-attachments/files/17280265/trinity.log)

**Comment by jjksaji** [comment]
I also attaching the  log file "/trinity/images/ubuntu/debootstrap/debootstrap.log"
[debootstrap.log](https://github.com/user-attachments/files/17280577/debootstrap.log)

**Comment by aphmschonewille** [comment]
we will publish a workaround for this problem. It's caused by the ubuntu team, where the rocky and alma repositories were not in sync yet.

**Comment by aphmschonewille** [comment]
today's push solved the above issue.
