### ISSUE TITLE
14.4 [bash ./INSTALL.sh ] fails on the part when it comes to "Disable all repo without '*-local* suffic"

### ISSUE THREAD

**Issue by jjksaji** [clustervision/trinityX#433]
Dear Team, 
I have been trying to do the setup, I am trying the release 14.4 on AlmaLinux 8 and Alma Linux 9 , in both the cases it was failing when it reaches the section  TASK [trinity/repos : Disable all repo without '*-local' suffix] 
posting it here, since the same occurrence happening every time I am trying with AlmaLinux 8 and Almalinux 9  

```
TASK [trinity/repos : Install yum-utils to make yum-config-manager available] 
changed: [controller1]
```

TASK [trinity/repos : Disable all repo without '*-local' suffix] 
fatal: [controller1]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, expand_argument_vars, removes, stdin, stdin_add_newline, strip_empty_ends."}

```
PLAY RECAP 
controller1                : ok=53   changed=18   unreachable=0    failed=1    skipped=43   rescued=0    ignored
```

**Comment by aphmschonewille** [comment]
Though we test Alma for release 8 and 9, we did not encounter this problem yet. The function/task is also not a required task. we will come with a solution shortly
