### ISSUE TITLE
"ansible-playbook compute-ubuntu.yml" for 14.4 and 14.3 crashes , point to RPM  repository  rather than to DEBian /Ubuntu repository 

### ISSUE THREAD

**Issue by jjksaji** [clustervision/trinityX#434]
Dear All, 
Good afternoon 
Like to update 
I have checked the "ansible-playbook compute-ubuntu.yml"  in 14.4 as well as 14.3 
In both the cases it crashes
Thanks 
Joseph John

**Comment by aphmschonewille** [comment]
crashes?

**Comment by jjksaji** [comment]
Yes, crashes ( I mean ansble playbook) all the time when running  "compute-ubuntu.yml"

**Comment by aphmschonewille** [comment]
would it be possible to pull the latest release/repo as quite a few problems have been resolved which might help you. also make sure the destination path/directory is removed before re-running the image creation playbook.

**Comment by jjksaji** [comment]
Thanks
Yesteday I tried with the latest release and I was able to complete it with
no problem
Thanks
Joseph John

**Comment by aphmschonewille** [comment]
alrighty..... closing issue.
