### ISSUE TITLE
TFTP services goes on dead on 14.4 release frequently

### ISSUE THREAD

**Issue by jjksaji** [clustervision/trinityX#435]
Noticed that TFTP service status goes to dead state, occasionally
screen shot attached for reference 

 
![image](https://github.com/user-attachments/assets/1965f71f-3709-495f-8b50-4490f8d95ed0)

**Comment by aphmschonewille** [comment]
it seems to be set as disabled. so it it didn't die, it just never started. The playbook would normally enable and start this service so i wonder if the playbook for controller reached the end. Can you please confirm that the whole playbook ran?

**Comment by bartlamboo** [comment]
This is normal behavior. The service is started whenever tftpd.socket is triggered. This used to be handled by xinetd before systemd sockets took this over.
