### ISSUE TITLE
Port 7051 , Nginx running , but iPXE boot process get stuck 

### ISSUE THREAD

**Issue by jjksaji** [clustervision/trinityX#436]
Hi, I have been trying iPXE boot for  14-4 and 13-4 on Alma Linux , the nodes does not pull the images, from the node, we can see that it is trying to contact http://[controller IP]:7051 , but it fails 
![image](https://github.com/user-attachments/assets/2821c1c8-dc45-427e-9c8e-ea92f012c04a)

When we check of the port 7051 in the controller we get the message it is been used by the web server Nginx and Nginx is running
![image](https://github.com/user-attachments/assets/a67491c3-267e-462a-ab78-f181e0a38724)

But the iPXE boot process get stuck

**Comment by aphmschonewille** [comment]
this would typically happen when the luna daemon is not running. could you please confirm that the whole controller playbook ran till completion without problems?

**Comment by aphmschonewille** [comment]
This issue was resolved as far as my memory serves. if not, please reopen.
