### ISSUE TITLE
obdol command not found, but from Web interface I can create and manage users

### ISSUE THREAD

**Issue by jjksaji** [clustervision/trinityX#438]
Dear All, 
Like to give this feedback on my HPC setup 
I have controller and nodes working fine, the web interface is working fine , I am able to create and manage users through the web interface, but from command line I cannot, on trouble shooting I found out that the "obdol" command itself note found 
Screenshot attached here for reference 
<img width="1019" alt="image" src="https://github.com/user-attachments/assets/5f17e304-bd92-4cce-bafb-41f3ca0766c8">
Thanks 
Joseph John

**Comment by sumit42876** [comment]
Dear @jjksaji ,
It seems there might be a slight error in your command. Did you mean "obol"?
If you're unsure, you can always get a detailed overview of the command and its options by running:
`obol --help`

**Comment by LokeshVemula** [comment]
Hi @sumit42876 ,

I've been facing the same error after configuring my controller.

![Image](https://github.com/user-attachments/assets/13dc589f-33be-45f1-be3c-3a4e9deeb966)

Can you help suggest where and what I need to check here ?
