### ISSUE TITLE
trinityX-14.4u1 , the DHCP IP given not start from the range we give 

### ISSUE THREAD

**Issue by jjksaji** [clustervision/trinityX#439]
HI All,
Good morning 
I have downloaded the latest trinityX-14.4u1  and did a installation 
I gave the following details in all.yaml file  

```
trix_cluster_dhcp_end: 192.168.1.60
trix_cluster_dhcp_start: 192.168.1.50
trix_cluster_net: 192.168.1.0
```

But  the Nodes are getting IP adress from 192.168.1.1 on wards, it is not following the above details from the all.yaml 
Like to give this feedback 
Thanks 
Joseph John

**Comment by Zeashh** [comment]
> which is the definition for the DHCP pool (of unknown machines)

Can you please explain this part a bit? What exactly are "unknown machines"? Worker/Login nodes with no definition? Clients?

Additionally, can nodes be automatically added to the cluster, or do all nodes need to be manually added using `luna node add` or other equivalents? TrinityX docs aren't very clear on this as far as I can tell.

**Comment by aphmschonewille** [comment]
Unknown machines are machines that are not assigned to luna, i.e. unknown MAC. The type of node is irrelevant. 

Automatic assignment can be enabled through: `luna cluster change --nextnode_discover y`
If that doesn't work, look at `luna cluster change -h` for the correct flag. This enabled means nodes being assigned automatically on a first come first serve basis
